//
//  ViewController.swift
//  hackthon
//
//  Created by Sarik Kumpan on 20/9/2562 BE.
//  Copyright © 2562 SandBlue. All rights reserved.
//

import UIKit
import Photos

class CamViewController: UIViewController {
    
    @IBOutlet fileprivate var captureButton: UIButton!
    
    ///Displays a preview of the video output generated by the device's cameras.
    @IBOutlet fileprivate var capturePreviewView: UIView!
    
    
    @IBOutlet weak var addFriend: UIButton!
    
    ///Allows the user to put the camera in photo mode.
//    @IBOutlet fileprivate var photoModeButton: UIButton!
//    @IBOutlet fileprivate var toggleCameraButton: UIButton!
//    @IBOutlet fileprivate var toggleFlashButton: UIButton!
    
    ///Allows the user to put the camera in video mode.
//    @IBOutlet fileprivate var videoModeButton: UIButton!
    
    let cameraController = CameraController()
    
    override var prefersStatusBarHidden: Bool { return true }
    
}

extension CamViewController {
    override func viewDidLoad() {
        
        func configureCameraController() {
            cameraController.prepare {(error) in
                if let error = error {
                    print(error)
                }
                
//                try? self.cameraController.displayPreview(on: self.capturePreviewView)
            }
        }
        
//        func styleCaptureButton() {
//            captureButton.layer.borderColor = UIColor.black.cgColor
//            captureButton.layer.borderWidth = 2
//
//            captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
//        }
//
//        styleCaptureButton()
        configureCameraController()
        
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
       let destVC : CameraSecondViewController = segue.destination as! CameraSecondViewController
//        destVC.dataLastFromPage = "test"
    }
}

extension CamViewController {

    
    @IBAction func captureImage(_ sender: UIButton) {
        cameraController.captureImage {(image, error) in
            guard let image = image else {
                print(error ?? "Image capture error")
                return
            }
            
            try? PHPhotoLibrary.shared().performChangesAndWait {
                PHAssetChangeRequest.creationRequestForAsset(from: image)
            }
        }
    }
    
    @IBAction func addFriend(_ sender: UIButton) {
        // perform segue
        performSegue(withIdentifier: "goAdd", sender: self)
    }
    
}



